(function installManualStarDeltaData(global) {
  "use strict";
  const platform = global.ECTPPlatform = global.ECTPPlatform || {}; platform.moduleData = platform.moduleData || {};
  const M = "ch02_manual_star_delta", id = (kind, name) => `${M}__${kind}__${name}`;
  const cmp = (name, device, type, partType, label, x, y, domain = "control") => Object.freeze({ schemaVersion:"1.0", componentId:id("cmp",name), deviceId:id("dev",device), type, partType, label:Object.freeze({text:label}), geometry:Object.freeze({x,y,width:64,height:42,orientation:0}), ports:Object.freeze([]), state:Object.freeze({}), circuitDomain:domain, behavior:partType });
  const wire = (name, domain, points) => Object.freeze({ wireId:id("wire",name), circuitDomain:domain, electricalRole:"supply", fromPort:id("port",`${name}_a`), toPort:id("port",`${name}_b`), routePoints:Object.freeze(points.map(([x,y])=>Object.freeze({x,y}))), phase:"" });
  const mainComponents = Object.freeze([cmp("qf1","qf1","breaker","main_contact","QF1",100,72,"main"),cmp("fu1","fu1","fuse","fuse_set","FU1",100,140,"main"),cmp("km_main","km","contactor","main_contact","KM",100,216,"main"),cmp("fr1","fr1","thermal_relay","thermal_element","FR",100,286,"main"),cmp("m1","m1","motor","six_terminal_motor","M 3~",100,385,"main"),cmp("kmy_main","kmy","contactor","star_contact","KMY",190,430,"main"),cmp("kmd_main","kmd","contactor","delta_contact","KMΔ",190,350,"main")]);
  const controlComponents = Object.freeze([cmp("fu2","fu2","fuse","control_fuse","FU2",350,72),cmp("fr_nc","fr1","thermal_relay","protection_nc","FR",420,120),cmp("sb3","sb3","push_button","nc","SB3 停止",490,120),cmp("sb1","sb1","push_button","no","SB1 星形",590,175),cmp("sb2","sb2","push_button","no","SB2 三角",590,270),cmp("km_coil","km","contactor","coil","KM",770,175),cmp("kmy_coil","kmy","contactor","coil","KMY",770,270),cmp("kmd_coil","kmd","contactor","coil","KMΔ",770,365)]);
  const mainWires = Object.freeze([wire("main_l1","main",[[56,36],[56,440]]),wire("main_l2","main",[[100,36],[100,440]]),wire("main_l3","main",[[144,36],[144,440]]),wire("star_link","main",[[100,385],[200,430]]),wire("delta_link","main",[[100,385],[200,350]])]);
  const controlWires = Object.freeze([wire("ctl_top","control",[[350,48],[350,420]]),wire("ctl_star","control",[[350,175],[810,175]]),wire("ctl_delta","control",[[350,270],[810,270]]),wire("ctl_main","control",[[350,365],[810,365]]),wire("ctl_return","control",[[840,48],[840,420]])]);
  platform.moduleData[M] = Object.freeze({ schemaVersion:"1.0", moduleId:M, geometryLockId:"ch02_manual_star_delta_geometry_v1_locked", referenceImages:Object.freeze(["./assets/reference/manual-star-delta.jpg"]), mainComponents, mainWires, controlComponents, controlWires, deviceEdges:Object.freeze([]) });
})(globalThis);
