(function installTimedAutoStopSolver(global) {
  "use strict";
  const platform=global.ECTPPlatform=global.ECTPPlatform||{}; platform.moduleSolvers=platform.moduleSolvers||{};
  const M="ch01_timed_auto_stop", D=(n)=>`${M}__dev__${n}`, W=(n)=>`${M}__wire__${n}`, clone=(v)=>JSON.parse(JSON.stringify(v));
  const fresh=()=>({operation:{power:"open",protection:"normal"},running:false,elapsed:0,completed:false,lastAction:{type:"RESET_MODULE",message:"模块已复位，等待合闸与启动。"},iterationCount:0});
  platform.moduleSolvers.createTimedAutoStopSolver=function(circuitData){let state=fresh();
    function solve(message=state.lastAction.message){if(state.operation.power!=="closed"||state.operation.protection!=="normal")state.running=false;if(state.elapsed>=120){state.elapsed=120;state.running=false;state.completed=true;}state.iterationCount=2;state.lastAction.message=message;return result();}
    function reset(){state=fresh();solve();return getState();}
    function dispatch(action){let message="状态已更新。";switch(action.type){case"POWER_CLOSE":state.operation.power="closed";message="QF1 合闸，定时控制回路待命。";break;case"POWER_OPEN":state.operation.power="open";state.running=false;state.elapsed=0;state.completed=false;message="QF1 分闸，KM1、KT1、KT2 全部释放。";break;case"START_FORWARD_PRESS":if(state.operation.power==="closed"){state.running=true;state.elapsed=0;state.completed=false;message="按下 SB1，KM1 自锁，电机运行并启动 KT1、KT2 计时。";}else message="QF1 未合闸，SB1 启动无效。";break;case"START_SECONDARY_PRESS":if(state.running){state.elapsed=Math.min(120,state.elapsed+30);message=state.elapsed>=120?"累计到 120 秒，KT2 延时常闭触点断开，KM1 释放，电机自动停止。":`计时推进到 ${state.elapsed} 秒，电机继续运行。`;}else message="电机未运行，计时不推进。";break;case"STOP_PRESS":state.running=false;state.elapsed=0;state.completed=false;message="人工停止，定时器复位。";break;case"RESET_MODULE":return reset();default:throw new Error(`${M} does not support ${action.type}`);}state.lastAction={type:action.type,message};return solve(message);}
    function result(){const on=state.running,powered=state.operation.power==="closed";return{schemaVersion:"1.0",moduleId:M,stableDeviceStates:{[D("km1")]:on,[D("kt1")]:on,[D("kt2")]:on},edgeStates:{},activeMainWireIds:on?circuitData.mainWires.map(x=>x.wireId):[],activeControlWireIds:on?circuitData.controlWires.map(x=>x.wireId):[],partialWireIds:powered&&!on?[W("ctl_supply")]:[],motorStates:{[D("m1")]:{state:on?"forward":"stopped",running:on,direction:on?"forward":"none"}},protectionStates:{},converged:true,iterationCount:state.iterationCount,lastAction:clone(state.lastAction),extension:{elapsedSeconds:state.elapsed,remainingSeconds:Math.max(0,120-state.elapsed),completed:state.completed,timerScale:"30s/step"}};}
    function getState(){return clone(state);}function validateGeometry(){const ws=[...circuitData.mainWires,...circuitData.controlWires],cs=[...circuitData.mainComponents,...circuitData.controlComponents],errors=[];if(ws.some(x=>!x.wireId.startsWith(`${M}__wire__`)||x.routePoints.length<2))errors.push("wire geometry/namespace mismatch");if(cs.some(x=>!x.componentId.startsWith(`${M}__cmp__`)))errors.push("component namespace mismatch");return{valid:!errors.length,errors,geometryLockId:circuitData.geometryLockId};}
    function runTests(){const saved=getState(),tests=[],check=(name,fn)=>{let passed=false,error="";try{passed=!!fn();}catch(e){error=String(e.message||e);}tests.push({name,passed,error});};reset();check("Geometry 与命名空间",()=>validateGeometry().valid);dispatch({type:"START_FORWARD_PRESS"});check("未合闸不能启动",()=>!state.running);dispatch({type:"POWER_CLOSE"});dispatch({type:"START_FORWARD_PRESS"});check("启动后 KM1 自锁且计时开始",()=>state.running&&state.elapsed===0);dispatch({type:"START_SECONDARY_PRESS"});check("每步推进 30 秒",()=>state.elapsed===30&&state.running);dispatch({type:"START_SECONDARY_PRESS"});dispatch({type:"START_SECONDARY_PRESS"});dispatch({type:"START_SECONDARY_PRESS"});check("120 秒自动停止",()=>!state.running&&state.completed&&state.elapsed===120);dispatch({type:"START_FORWARD_PRESS"});check("停止后可重新启动并清零",()=>state.running&&state.elapsed===0);dispatch({type:"POWER_OPEN"});check("分闸释放全部执行元件",()=>!state.running&&!result().stableDeviceStates[D("kt1")]);state=saved;solve(saved.lastAction.message);return{passed:tests.filter(x=>x.passed).length,total:tests.length,results:tests};}
    solve();return Object.freeze({reset,dispatch,solve,getState,getSolverResult:result,validateGeometry,runTests});};
})(globalThis);
